### ISSUE TITLE
Reduce heading level of 01_example-CCMP-notebook

### ISSUE THREAD

**Issue by rabernat** [cgentemann/pangeo_ccmp#1]
As you can see from the [built version of the notebook](http://gallery.pangeo.io/repos/cgentemann/pangeo_ccmp/01_example-CCMP-notebook.html), `01_example-CCMP-notebook.ipynb` has some weird heading issues going on. 

I think the problem is that you have too many H1-level headings, e.g.

```
# Title
# Another Top Level Header 
```

Instead, reduce the header level of the subtitles / headers elsewhere in the notebook, such that you have only on H1-level title. This will become the notebook title in Pangeo Gallery. E.g.

```
# Title
## Header
```

**Comment by cgentemann** [comment]
Fixed! https://github.com/cgentemann/pangeo_ccmp/commit/b39937f191c855027d9ffed83e80a3c37a3e1e8a
