### ISSUE TITLE
Fix for failing percentile calculation

### ISSUE THREAD

**Issue by rabernat** [cgentemann/pangeo_ccmp#2]
Here is a better way to compute the fraction of time the wind is in a certain range

```python
from xhistogram.xarray import histogram
wspd_levels = np.array([0, 2, 10, 1000])
wspd_hist = histogram(ds_ccmp.wspd, bins=[wspd_levels], dim=['time'], density=True)
wspd_hist.load()
```

However, I still couldn't manage to get the computation to run without workers dying. Frustrating.

**Comment by cgentemann** [comment]
Dying on me as well. I've had this problem with xhistogram before.
Your code 100% easier to understand and read than my cludgy fix to avoid this issue, but better to try and find an actual solution that uses xhistogram. 
When I run --- Dask has a *lot* of red. I checked & dask version is 2021.1.1 and I wonder if we upgraded to 2021.7.1 or > with the new memory management if this might go away?

**Comment by cgentemann** [comment]
subsetted data to deal with for tutorial --- closing issue but would be good to get to the bottom of what is going on at some point.
